#!/usr/bin/env bash
#asdasdd asdasdasdsas
echo $$ > /var/run/myscript.pid
while true
do
	sleep 2
	echo "To infinity and beyond"
	trap "echo I hate the kill command ; rm /var/run/myscript.pid ; exit" SIGTERM
	trap "echo Y U no love me?!" SIGINT
	trap "rm -rf /var/run/myscript.pid ; exit" SIGQUIT
done
